Short circuit scripts with some helpful messages

diff --git a/build-python b/build-python
--- a/build-python
+++ b/build-python
@@ -1,10 +1,18 @@
 #!/usr/bin/env bash
 
 set -o errexit
-set -o xtrace
 
-[[ $INSTALL_DEST ]]
-[[ $VERSION ]]
+if [[ ! $INSTALL_DEST ]] ; then
+  echo 'Missing INSTALL_DEST'
+  exit 1
+fi
+
+if [[ ! $VERSION ]] ; then
+  echo 'Missing $VERSION'
+  exit 1
+fi
+
+set -o xtrace
 
 sudo env PYTHON_BUILD_ROOT=/opt/pyenv/plugins/python-build \
   /opt/pyenv/plugins/python-build/bin/python-build $VERSION $INSTALL_DEST/$VERSION
diff --git a/create-archive b/create-archive
--- a/create-archive
+++ b/create-archive
@@ -1,11 +1,23 @@
 #!/usr/bin/env bash
 
 set -o errexit
-set -o xtrace
 
-[[ $LSB_RELEASE ]]
-[[ $INSTALL_DEST ]]
-[[ $VERSION ]]
+if [[ ! $LSB_RELEASE ]] ; then
+  echo 'Missing LSB_RELEASE'
+  exit 1
+fi
+
+if [[ ! $INSTALL_DEST ]] ; then
+  echo 'Missing INSTALL_DEST'
+  exit 1
+fi
+
+if [[ ! $VERSION ]] ; then
+  echo 'Missing VERSION'
+  exit 1
+fi
+
+set -o xtrace
 
 : ${TAR_PATHS:=}
 : ${DEST:=${1}}
